<t_main> ::= "ricci" "{" [<t_var>] <t_command> "}"

<t_var> ::= "var" "[" <t_declaration> "]"

<t_declaration> ::= <t_type> <t_id> <t_end> | 
                <t_type> <t_id> <t_end> <t_declaration>

<t_type> ::= "int" | "double" | "char" | "string" | "bool"

<t_end> ::= ";"

<t_command> ::= (<t_att> <t_end> | <t_decision> | <t_repetition>) | 
            (<t_att> <t_end> | <t_decision> | <t_repetition>) <t_command>

<t_att> ::= (<t_id> "=" (<t_id> | <t_num> | <t_operation> | <t_char> | <t_bool> | <t_str>) | 
            <t_id>"++" | <t_id>"--") <t_end>

<t_operation> ::= (<t_id> | <t_num>) <t_op> (<t_id> | <t_num>)

<t_op> ::= "+" | "-" | "*" | "/"

<t_decision> ::= <t_if>

<t_repetition> ::= <t_while> | <t_for>

<t_if> ::= "if" "(" <t_condition> ")" "{" <t_command> "}" [<t_else>]

<t_else> ::= "else" "{" <t_command> "}"

<t_condition> ::= <t_logicC> | <t_relationalC>

<t_while> ::= "while" "(" <t_condition> ")" "{" <t_command> "}"

<t_for> ::= "for" "(" <t_att><t_end><t_condition><t_end><t_att><t_end>")" "{" <t_command> "}"

<t_logicC> ::= ["!"] (<t_id> | <t_bool> | <t_relationalC>) [<t_logicCPlus>]

<t_logicCPlus> ::= ("&&" | "||" ) ["!"] (<t_relationalC> | <t_id> | <t_bool>) | 
                    <t_logicCPlus>

<t_relationalC> ::= "$"(<t_num> | <t_id>) <t_relational> (<t_num> | <t_id>)"$"

<t_relational> ::= ">" | "<"| ">= "| "<=" | "==" | "!="

<t_id> ::= (a..z | _)(a..z | _ | 0..9)*

<t_num> 0..9+ | 0..9+"."0..9+ | "-"0..9+ | "-"0..9+"."0..9+

<t_bool> :: "true" | "false"

<t_char> "'" (<t_character> | <t_dig>) "'"

<t_str> """ (a..z | _ | ! | @ | $ | % | & | * | ( | ) | = | + | - | _ | / | . | , | ; | : | ? | 0..9)* """

<t_dig> ::= 0..9

<t_character> ::= a..z | A..Z

<Keyword> ::= bool | case | char | double | else | for | if | int | while | main | string

/************    FIRST    ************/

<t_main> ::= {"ricci"}
<t_id> ::= {"var"}
<t_declaration> ::= {"int", "double", "char", "string", "bool"}
<t_type> ::= {"int", "double", "char", "string", "bool"}
<t_end> ::= {";"}
<t_command> ::= {variavel, "if", "while", "for"}
<t_att> ::= {variavel}
<t_operation> ::= {variavel, num}
<t_op> ::= {"+", "-", "*", "/"}
<t_decision> ::= {"if"}
<t_repetition> ::= {"while", "for"}
<t_if> ::= {"if"}
<t_else> :: = {"else"}
<t_condition> ::= {"!", variavel, "true", "false", num}
<t_while> ::= {"while"}
<t_for> ::= {"for"}
<t_logicC> ::= {"!", variavel, "true", "false", num, "$"}
<t_logicCPlus> ::= {"&&", "||"}
<t_relationalC> ::= {"$"}
<t_relational> ::= {">", "<", ">=", "<=", "==", "!="}
<t_id> ::= {variavel}
<t_num> ::= {num}
<t_bool> ::= {"true", "false"}
<t_char> ::= {"'"}
<t_str> ::= {"\""}
<t_dig> ::= {num}
<t_character> ::= {variavel}

/***********    FOLLOW    ***********/
<t_main> ::= {"$"}
<t_var> ::= {variavel, "if", "while", "for"}
<t_declaration> ::= {"]"}
<t_type> ::= {variavel}
<t_end> ::= {"int", "double", "char", "string", "bool", "while", "for", variavel}
<t_command> ::= {"}", variavel, "if", "while", "for"}
<t_att> ::= {";", variavel, "if", "while", "for"}
<t_operation> ::= {";"}
<t_op> ::= {variavel, num}
<t_decision> ::= {"}", variavel, "if", "while", "for"}
<t_repetition> ::= {"}", variavel, "if", "while", "for"}
<t_if> ::= {"}", variavel, "if", "while", "for"}
<t_else> ::= {"}", variavel, "if", "while", "for"}
<t_condition> ::= {")", ";"}
<t_while> ::= {"}", variavel, "if", "while", "for"}
<t_for> ::= {"}", variavel, "if", "while", "for"}
<t_logicC> ::= {")", ";"}
<t_logicCPlus> ::= {")", ";", "&&", "||"}
<t_relationalC> ::= {")", ";", "&&", "||"}
<t_relational> ::= {num, variavel}
<t_id> ::= {";", "=", "++", "--", ")", "&&", "||", ">", "<", ">= ", "<=", "==", "!="}
<t_num> ::= {";", "+", "-", "*", "/", ">", "<", ">=", "<=", "==", "!=", ")"}
<t_bool> ::= {";", ")", "&&", "||"}
<t_char> ::= {";"}
<t_str> ::= {";"}
<t_dig> ::= {"'"}
<t_character> ::= "/"" 